### ISSUE TITLE
Missing sub-modules on Hackage?

### ISSUE THREAD

**Issue by sigrdrifa** [TristanCacqueray/haskell-xstatic#2]
Hey, I was trying to build one of the demos but it is complaining that it cannot find the packages: xstatic-htmx and xstatic-tailwind - and indeed they don't seem to be on hackage: https://hackage.haskell.org/package/xstatic-htmx and the main xstatic package does not seem to export the modules.

Do you know what happened to them?

**Comment by TristanCacqueray** [comment]
Hello, yes I have not yet published the JS bundles to hackage. Though running the demos from the repo should work because the packages are exposed through the `cabal.project`. There are also instructions to pull the packages using a `source-repository-package` directive. Could you please share the error you got?

I guess it should be fine to publish htmx and tailwind to hackage, but I was worrying about the code duplication by doing so.

**Comment by sigrdrifa** [comment]
Ah thank you! I didn't consider the cabal.project exposing the packages, thanks! 

I'll try the source-repositry-package approach too
